### ISSUE TITLE
Competition Pressure

### ISSUE THREAD

**Issue by lsandig** [ehsan66/ICAOD#2]
Another discrepancy: the [article](https://dx.doi.org/10.1016/j.csda.2016.06.014) states on p. 7, first paragraph, that

> ICA performs a competition if and only if a randomly generated number between 0 and 1 exceeds 0.11

but the code seems to be the other way around:

https://github.com/ehsan66/ICAOD/blob/08a95cf543c6ac7dbd216efe5f85f02783d87538/R/2-InternalCommonFunctions.R#L330-L339

Which version is correct?

**Comment by ehsan66** [comment]
This is correct. If the random number greater than .11 l, it will not proceed and return Empires and exit the function

**Comment by ehsan66** [comment]
Both versions should be correct. As I remember, in the manuscript for the sake of simplicity for a minmax problem, the algorithm for a maximization problem was intruduced. Here, it could be the minimazion problem.
But I dont have the manuscript to check.

**Comment by lsandig** [comment]
Thank you for the clarification!
