### ISSUE TITLE
Bug in `UniteSimilarEmpires`?

### ISSUE THREAD

**Issue by lsandig** [ehsan66/ICAOD#3]
I suspect that the nested `while` loops here are not correct. It seems to me that they should iterate over and compare all (unique) pairs of empires. As it is, only empires with `counter1 == 1` are considered.

https://github.com/ehsan66/ICAOD/blob/08a95cf543c6ac7dbd216efe5f85f02783d87538/R/2-InternalCommonFunctions.R#L510-L542

Is there a `counter2 <- counter1 + 1` missing after line 541?

**Comment by ehsan66** [comment]
no it is correct. There are two counters in the loop and they both are updated

**Comment by ehsan66** [comment]
Both versions should be correct. As I remember, in the manuscript for the sake of simplicity for a min**max** problem, the algorithm for a maximization problem was intruduced. Here, it could be the minimazion problem. 
But I dont have the manuscript to check.

**Comment by lsandig** [comment]
Let me give an example of what I mean. Let's assume we have `NumOfEmpires == 4`. Replacing the actual uniting with a print statement (for brevity), the current code effectively boils down to
```r
counter1 <- 1
counter2 <- 2
while(counter1 <= (NumOfEmpires-1)){
  while(counter2 <= NumOfEmpires){
    cat("Trying to unite empire", counter1, "with empire", counter2, "\n")
    counter2 <- counter2 + 1
  }
  counter1 <- counter1 + 1
}
```
When executed, this prints
```
Trying to unite empire 1 with empire 2
Trying to unite empire 1 with empire 3
Trying to unite empire 1 with empire 4
```
i.e. the combinations `(2,3)`, `(2,4)`, and `(3,4)` are never looked at.
My suggestion what to do instead is
```r
counter1 <- 1
counter2 <- 2
while(counter1 <= (NumOfEmpires-1)){
  while(counter2 <= NumOfEmpires){
    cat("Trying to unite empire", counter1, "with empire", counter2, "\n")
    counter2 <- counter2 + 1
  }
  counter1 <- counter1 + 1
  counter2 <- counter1 + 1 # only this line changed
}
```
which gives
```
Trying to unite empire 1 with empire 2
Trying to unite empire 1 with empire 3
Trying to unite empire 1 with empire 4
Trying to unite empire 2 with empire 3
Trying to unite empire 2 with empire 4
Trying to unite empire 3 with empire 4
```

**Comment by ehsan66** [comment]
you are right, Thanks, I will apply our suggestion in the next update.  However, it could take long as I should check all the produced examples again

**Comment by ehsan66** [comment]
As this is not really an issue and does not influence the performance of the algorithm, I close it and will do it in the next update
